const unicompare = require('../src/unicompare')
const jsn1 = require('./data1.json')
const jsn2 = require('./copyOfData1.json')
const diffJsn = require('./copyOfData1WithWrongParam.json')
const deepSomeTest = require('./deepSomeTest.json')

console.log("Testing unicompare")
console.log("")
console.log("[ objEqual ] TEST equal objects with deep are equal : ", unicompare.objEqual(jsn1, jsn2, true))
console.log("[ objEqual ] TEST equal objects without deep are equal : ", unicompare.objEqual(jsn1, jsn2, false))
console.log("[ objEqual ] TEST different objects with deep are equal :  ", unicompare.objEqual(jsn1, diffJsn, true))
console.log("[ objEqual ] TEST different objects without deep are equal : ", unicompare.objEqual(jsn1, diffJsn, false))
console.log("")
console.log("[ some ] TEST an object that contains the array i want to find: ", unicompare.some({test:[1,2,3]}, [1,2,3]))
console.log("[ some ] TEST an object that contains the array i want to find ( ULTRA DEEP TEST ): ", unicompare.some(deepSomeTest, [1,2,3]))